create table boxes (
    id bigint generated by default as identity,
    parent_id bigint, user_id bigint,
    name varchar(100),
    primary key (id)
);
create table items (
    id integer generated by default as identity, box_id bigint, primary key (id)
);
create table users (
    id bigint generated by default as identity,
    email varchar(255),
    name varchar(255),
    password varchar(255),
    primary key (id)
);
alter table if exists boxes add constraint FK9vl07o37n78yuv4jim6x8id7h foreign key (parent_id) references boxes;
alter table if exists boxes add constraint FKk7jb0e48vmiyhp2nd7psv1x8t foreign key (user_id) references users;
alter table if exists items add constraint FK3ajgioeb0uvkjt5rlbstqxuuw foreign key (box_id) references boxes;