CREATE TABLE invitation_codes (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  code VARCHAR(20) NOT NULL,
                                  creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                  expiration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                  email VARCHAR(255) NOT NULL,
                                  CONSTRAINT pk_invitation_codes PRIMARY KEY (id)
);

-- Índice composto (email e código)
CREATE INDEX idx_invitation_codes_email_code
    ON invitation_codes (email, code);